// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameArticle = "article"

// Article mapped from table <article>
type Article struct {
	ID             int        `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UserID         int        `gorm:"column:user_id;type:int;not null" json:"user_id"`                      // 作者
	CategoryID     *int       `gorm:"column:category_id;type:int" json:"category_id"`                       // 文章分类
	ArticleCover   *string    `gorm:"column:article_cover;type:varchar(1024)" json:"article_cover"`         // 文章缩略图
	ArticleTitle   string     `gorm:"column:article_title;type:varchar(50);not null" json:"article_title"`  // 标题
	ArticleContent string     `gorm:"column:article_content;type:longtext;not null" json:"article_content"` // 内容
	Type           int        `gorm:"column:type;type:tinyint;not null" json:"type"`                        // 文章类型 1原创 2转载 3翻译
	OriginalURL    *string    `gorm:"column:original_url;type:varchar(255)" json:"original_url"`            // 原文链接
	IsTop          int        `gorm:"column:is_top;type:tinyint(1);not null" json:"is_top"`                 // 是否置顶 0否 1是
	IsDelete       int        `gorm:"column:is_delete;type:tinyint(1);not null" json:"is_delete"`           // 是否删除  0否 1是
	Status         *int       `gorm:"column:status;type:tinyint;not null;default:1" json:"status"`          // 状态值 1公开 2私密 3评论可见
	CreatedAt      time.Time  `gorm:"column:created_at;type:datetime;not null" json:"created_at"`           // 发表时间
	UpdatedAt      *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`                    // 更新时间
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
