// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameCOLUMNS = "COLUMNS"

// COLUMNS mapped from table <COLUMNS>
type COLUMNS struct {
	TABLECATALOG           *string `gorm:"column:TABLE_CATALOG;type:varchar(64)" json:"TABLE_CATALOG"`
	TABLESCHEMA            *string `gorm:"column:TABLE_SCHEMA;type:varchar(64)" json:"TABLE_SCHEMA"`
	TABLENAME              *string `gorm:"column:TABLE_NAME;type:varchar(64)" json:"TABLE_NAME"`
	COLUMNNAME             *string `gorm:"column:COLUMN_NAME;type:varchar(64)" json:"COLUMN_NAME"`
	ORDINALPOSITION        uint    `gorm:"column:ORDINAL_POSITION;type:int unsigned;not null" json:"ORDINAL_POSITION"`
	COLUMNDEFAULT          *string `gorm:"column:COLUMN_DEFAULT;type:text" json:"COLUMN_DEFAULT"`
	ISNULLABLE             string  `gorm:"column:IS_NULLABLE;type:varchar(3);not null" json:"IS_NULLABLE"`
	DATATYPE               *string `gorm:"column:DATA_TYPE;type:longtext" json:"DATA_TYPE"`
	CHARACTERMAXIMUMLENGTH *int    `gorm:"column:CHARACTER_MAXIMUM_LENGTH;type:bigint" json:"CHARACTER_MAXIMUM_LENGTH"`
	CHARACTEROCTETLENGTH   *int    `gorm:"column:CHARACTER_OCTET_LENGTH;type:bigint" json:"CHARACTER_OCTET_LENGTH"`
	NUMERICPRECISION       *uint   `gorm:"column:NUMERIC_PRECISION;type:bigint unsigned" json:"NUMERIC_PRECISION"`
	NUMERICSCALE           *uint   `gorm:"column:NUMERIC_SCALE;type:bigint unsigned" json:"NUMERIC_SCALE"`
	DATETIMEPRECISION      *uint   `gorm:"column:DATETIME_PRECISION;type:int unsigned" json:"DATETIME_PRECISION"`
	CHARACTERSETNAME       *string `gorm:"column:CHARACTER_SET_NAME;type:varchar(64)" json:"CHARACTER_SET_NAME"`
	COLLATIONNAME          *string `gorm:"column:COLLATION_NAME;type:varchar(64)" json:"COLLATION_NAME"`
	COLUMNTYPE             string  `gorm:"column:COLUMN_TYPE;type:mediumtext;not null" json:"COLUMN_TYPE"`
	COLUMNKEY              string  `gorm:"column:COLUMN_KEY;type:enum('','PRI','UNI','MUL');not null" json:"COLUMN_KEY"`
	EXTRA                  *string `gorm:"column:EXTRA;type:varchar(256)" json:"EXTRA"`
	PRIVILEGES             *string `gorm:"column:PRIVILEGES;type:varchar(154)" json:"PRIVILEGES"`
	COLUMNCOMMENT          string  `gorm:"column:COLUMN_COMMENT;type:text;not null" json:"COLUMN_COMMENT"`
	GENERATIONEXPRESSION   string  `gorm:"column:GENERATION_EXPRESSION;type:longtext;not null" json:"GENERATION_EXPRESSION"`
	SRSID                  *uint   `gorm:"column:SRS_ID;type:int unsigned" json:"SRS_ID"`
}

// TableName COLUMNS's table name
func (*COLUMNS) TableName() string {
	return TableNameCOLUMNS
}
