// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"fmt"
	"testing"

	"github.com/ve-weiyi/go-sdk/utils/generate/blog/entity"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&entity.Article{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&entity.Article{}) fail: %s", err)
	}
}

func Test_articleQuery(t *testing.T) {
	article := newArticle(db)
	article = *article.As(article.TableName())
	_do := article.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(article.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <article> fail:", err)
		return
	}

	_, ok := article.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from article success")
	}

	err = _do.Create(&entity.Article{})
	if err != nil {
		t.Error("create item in table <article> fail:", err)
	}

	err = _do.Save(&entity.Article{})
	if err != nil {
		t.Error("create item in table <article> fail:", err)
	}

	err = _do.CreateInBatches([]*entity.Article{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <article> fail:", err)
	}

	_, err = _do.Select(article.ALL).Take()
	if err != nil {
		t.Error("Take() on table <article> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <article> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <article> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <article> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*entity.Article{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <article> fail:", err)
	}

	_, err = _do.Select(article.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <article> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <article> fail:", err)
	}

	_, err = _do.Select(article.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <article> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <article> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <article> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <article> fail:", err)
	}

	_, err = _do.ScanByPage(&entity.Article{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <article> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <article> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <article> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <article> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <article> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <article> fail:", err)
	}
}
