// Code generated by github.com/ve-weiyi/ve-admin-store/server
// Code generated by github.com/ve-weiyi/ve-admin-store/server
// Code generated by github.com/ve-weiyi/ve-admin-store/server

package entity

// TableNameAuth return the table name of <auth>
const TableNameAuth = "auth"

// Auth mapped from table <auth>
type Auth struct {
}
